name: Prompt Injection Collective
title: Prompt Injection Collective
subtitle: World's First & Most Famous Prompt Injection Directory - A Collective Initiative 

github_pages:
  url: "promptinjection.github.io"
  branch: "main"
