name: RED TEAM COLLECTIVE
title: RED TEAM COLLECTIVE
subtitle: "SYSTEM BREACH DETECTED - Elite Hacking Arsenal - Cyber Warfare Division"

github_pages:
  url: "promptinjection.github.io"
  branch: "main"
